### ISSUE TITLE
SQL execution support

### ISSUE THREAD

**Issue by encephalone** [Flowneee/tarantool-rs#6]
Please add the ability to execute SQL queries with parameter binding. 
Implementation example: https://github.com/zheludkovm/RustyTarantool.

**Comment by Flowneee** [comment]
Implemented in version `0.0.7`. There is still no documentation, but you can check `examples/sql.rs`, there is pretty much everything.

Note that by default statements are prepared and cached even if you do not explicitly call `prepare_sql`, that should provide reasonable performance with just calling `execute_sql` repeatedly (although it wasn't tested _yet_). You can disable this behavior by setting `Builder::sql_statement_cache_capacity` to 0.

**Comment by encephalone** [comment]
Nice!
